<?php
/**
 * Plugin Name:       PomoloBee WP
 * Description:       FSE block hosting a React SPA that talks to Django.
 * Version:           1.0.0
 * Author:            Nathabee
 */

/**
 * 1) Register blocks from build/
 */
if ( function_exists( 'wp_register_block_types_from_metadata_collection' ) ) {
    add_action( 'init', function () {
        wp_register_block_types_from_metadata_collection(
            __DIR__ . '/build',
            __DIR__ . '/build/blocks-manifest.php'
        );
    } );
}

/**
 * 2) Register a CPT to host the SPA (one post with slug "pomolobee")
 *    We drive permalinks via our rewrite rule, so set rewrite => false.
 */
function pomolobee_register_cpt() {
    register_post_type( 'pomolobee_page', [
        'label'               => 'Pomolobee Pages',
        'public'              => true,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_rest'        => true,
        'has_archive'         => false,
        'rewrite'             => false,
        'supports'            => [ 'title', 'editor' ],
        'show_in_nav_menus'   => false,
        'exclude_from_search' => true,
        'menu_position'       => 20,
        'menu_icon'           => 'dashicons-chart-line',
    ] );
}
add_action( 'init', 'pomolobee_register_cpt' );

/**
 * 3) Activation: create the container post (slug = pomolobee) and flush rules
 */
function pomolobee_activate() {
    pomolobee_register_cpt();

    $slug  = 'pomolobee';
    $type  = 'pomolobee_page';
    $title = 'PomoloBee';
    $block = '<!-- wp:pomolobee/pomolobee-app /-->';

    if ( ! get_page_by_path( $slug, OBJECT, $type ) ) {
        wp_insert_post( [
            'post_title'   => $title,
            'post_name'    => $slug,
            'post_content' => $block,
            'post_status'  => 'publish',
            'post_type'    => $type,
        ] );
    }

    // Ensure our rewrite rule below is applied.
    flush_rewrite_rules();
}
register_activation_hook( __FILE__, 'pomolobee_activate' );
register_deactivation_hook( __FILE__, 'flush_rewrite_rules' );

/**
 * 4) Deep-linking: route /pomolobee and /pomolobee/* to the single CPT post
 *    One rule is enough.
 */
add_action( 'init', function () {
    add_rewrite_rule(
        '^pomolobee(?:/.*)?$',
        'index.php?post_type=pomolobee_page&name=pomolobee',
        'top'
    );
} );

/**
 * 5) Front-end styles (Bootstrap)
 */
add_action( 'wp_enqueue_scripts', function () {
    wp_enqueue_style(
        'pomolobee-bootstrap',
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css',
        [],
        null
    );
} );

/**
 * 6) Enqueue + localize the SPA bundle ONLY on the container page.
 *    (This replaces the enqueue_block_assets localization to avoid duplicates.)
 */
add_action( 'wp_enqueue_scripts', function () {
    if ( ! is_singular( 'pomolobee_page' ) ) {
        return;
    }

    // Use the asset file generated by @wordpress/scripts so deps/versions are correct.
    $asset_path = __DIR__ . '/build/pomolobee-app/view.asset.php';
    $asset      = file_exists( $asset_path ) ? include $asset_path : ['dependencies' => [], 'version' => null];

    wp_enqueue_script(
        'pomolobee-pomolobee-app-view',
        plugins_url( 'build/pomolobee-app/view.js', __FILE__ ),
        $asset['dependencies'],
        $asset['version'],
        true
    );

    $api_url = get_option( 'pomolobee_api_url', 'http://localhost:9001/api' );

    wp_localize_script( 'pomolobee-pomolobee-app-view', 'pomolobeeSettings', [
        'apiUrl'    => trailingslashit( $api_url ),
        'basename'  => '/pomolobee', // React Router basename
        'errorPath' => '/error',     // Route within the SPA (relative to basename)
    ] );
}, 20 );

/**
 * 7) Settings page for API base URL
 */
add_action( 'admin_menu', function () {
    add_options_page(
        'PomoloBee Settings',
        'PomoloBee Settings',
        'manage_options',
        'pomolobee-settings',
        'pomolobee_settings_page_html'
    );
} );

add_action( 'admin_init', function () {
    register_setting( 'pomolobee_settings_group', 'pomolobee_api_url' );

    add_settings_section(
        'pomolobee_main_section',
        'Main Settings',
        null,
        'pomolobee-settings'
    );

    add_settings_field(
        'pomolobee_api_url',
        'API Base URL for Pomolobee',
        'pomolobee_api_url_render',
        'pomolobee-settings',
        'pomolobee_main_section'
    );
} );

function pomolobee_api_url_render() {
    $value = get_option( 'pomolobee_api_url', 'http://localhost:9001/api' );
    echo "<input type='text' name='pomolobee_api_url' value='" . esc_attr( $value ) . "' size='50'>";
}

function pomolobee_settings_page_html() { ?>
    <div class="wrap">
        <h1>PomoloBee Plugin Settings</h1>
        <form method="post" action="options.php">
            <?php
            settings_fields( 'pomolobee_settings_group' );
            do_settings_sections( 'pomolobee-settings' );
            submit_button();
            ?>
        </form>
    </div>
<?php }

/**
 * 8) Optional: log our script handles for debugging
 */
add_action( 'wp_print_scripts', function () {
    if ( is_admin() ) return;
    global $wp_scripts;
    foreach ( $wp_scripts->registered as $handle => $script ) {
        if ( str_contains( $handle, 'pomolobee' ) ) {
            error_log( "🧩 PomoloBee script handle: $handle" );
        }
    }
} );
