# Generated by Django 5.2.8 on 2025-11-27 19:59

import BeeFontCore.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('alphabet', models.TextField()),
            ],
            options={
                'verbose_name': 'Supported language',
                'verbose_name_plural': 'Supported languages',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDefinition',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('page_format', models.CharField(default='A4', max_length=16)),
                ('dpi', models.IntegerField(default=300)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('paper_width_mm', models.FloatField(default=210.0)),
                ('paper_height_mm', models.FloatField(default=297.0)),
                ('cell_width_mm', models.FloatField(default=30.0)),
                ('cell_height_mm', models.FloatField(default=30.0)),
                ('margin_left_mm', models.FloatField(default=20.0)),
                ('margin_top_mm', models.FloatField(default=20.0)),
                ('fiducial_size_mm', models.FloatField(default=10.0)),
                ('fiducial_margin_mm', models.FloatField(default=5.0)),
                ('gap_x_mm', models.FloatField(default=0.0)),
                ('gap_y_mm', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Template definition',
                'verbose_name_plural': 'Template definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FontJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(default=BeeFontCore.models.generate_sid, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_family', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Font job',
                'verbose_name_plural': 'Font jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_index', models.IntegerField()),
                ('letters', models.TextField(blank=True)),
                ('scan_image_path', models.CharField(blank=True, max_length=512)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='beefontcore.fontjob')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beefontcore.templatedefinition')),
            ],
            options={
                'verbose_name': 'Job page',
                'verbose_name_plural': 'Job pages',
                'ordering': ['job', 'page_index'],
                'unique_together': {('job', 'page_index')},
            },
        ),
        migrations.CreateModel(
            name='Glyph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_index', models.IntegerField()),
                ('letter', models.CharField(max_length=8)),
                ('variant_index', models.IntegerField()),
                ('image_path', models.CharField(max_length=512)),
                ('formattype', models.CharField(choices=[('png', 'PNG bitmap'), ('svg', 'SVG vector')], default='png', max_length=8)),
                ('is_default', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glyphs', to='beefontcore.fontjob')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glyphs', to='beefontcore.jobpage')),
            ],
            options={
                'verbose_name': 'Glyph',
                'verbose_name_plural': 'Glyphs',
                'ordering': ['job', 'letter', 'formattype', 'variant_index'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('job', 'letter', 'formattype'), name='unique_default_glyph_per_job_letter_formattype')],
                'unique_together': {('job', 'letter', 'formattype', 'variant_index')},
            },
        ),
        migrations.CreateModel(
            name='FontBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ttf_path', models.CharField(max_length=512)),
                ('log', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('glyph_formattype', models.CharField(choices=[('png', 'PNG bitmap'), ('svg', 'SVG vector')], default='png', max_length=8)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='beefontcore.fontjob')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beefontcore.supportedlanguage')),
            ],
            options={
                'verbose_name': 'Font build',
                'verbose_name_plural': 'Font builds',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'language', 'glyph_formattype')},
            },
        ),
    ]
