# Generated by Django 5.2.8 on 2025-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='queued', max_length=12)),
                ('family', models.CharField(default='MyHand', max_length=80)),
                ('upload', models.FileField(upload_to='beefont/uploads/')),
                ('template_name', models.CharField(default='A4_10x10', max_length=64)),
                ('log', models.TextField(blank=True, default='')),
                ('segments_dir', models.CharField(blank=True, default='', max_length=255)),
                ('ttf_path', models.FileField(blank=True, null=True, upload_to='beefont/builds/')),
                ('zip_path', models.FileField(blank=True, null=True, upload_to='beefont/builds/')),
            ],
        ),
    ]
