# Generated by Django 5.2.8 on 2025-11-15 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeeFontCore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='job',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='upload',
        ),
        migrations.AddField(
            model_name='job',
            name='characters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(default='DE', max_length=8),
        ),
        migrations.AddField(
            model_name='job',
            name='page_format',
            field=models.CharField(default='A4', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beefont_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('in_progress', 'IN_PROGRESS'), ('ready_for_font', 'READY_FOR_FONT'), ('font_generated', 'FONT_GENERATED'), ('cancelled', 'CANCELLED')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='TemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=64)),
                ('page_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('no_scan', 'NO_SCAN'), ('analyzed', 'ANALYZED'), ('error', 'ERROR'), ('approved', 'APPROVED'), ('UPLOADED', 'UPLOADED')], default='no_scan', max_length=16)),
                ('scan_original_path', models.CharField(blank=True, default='', max_length=255)),
                ('scan_processed_path', models.CharField(blank=True, default='', max_length=255)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='BeeFontCore.job')),
            ],
            options={
                'ordering': ('job', 'template_code', 'page_index'),
            },
        ),
    ]
