# Generated by Django 5.2.8 on 2025-11-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beefontcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glyph',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glyphs', to='beefontcore.jobpage'),
        ),
    ]
