# Generated by Django 5.2.8 on 2025-11-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeeFontCore', '0002_alter_job_options_remove_job_template_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='templateslot',
            name='status',
            field=models.CharField(choices=[('no_scan', 'NO_SCAN'), ('analyzed', 'ANALYZED'), ('error', 'ERROR'), ('approved', 'APPROVED'), ('uploaded', 'UPLOADED')], default='no_scan', max_length=16),
        ),
    ]
