// src/mytypes/glyphEditor.ts

 
// ---------------------------------------------------------------------------
// SVG letter skeleton types (logical coordinates, not pixels)
// ---------------------------------------------------------------------------

/**
 * Handwriting-style 5-line system anchors.
 * These are logical lines, not pixel coordinates.
 */
export type GlyphSkeletonAnchor =
  | 'majuscule'
  | 'ascender'
  | 'xheight'
  | 'baseline'
  | 'descender';

/**
 * Logical anchor-based point (relative, not absolute pixels).
 */
export type GlyphSkeletonPoint = {
  /**
   * Relative X position in [0, 1].
   * 0   = left “ink box” edge,
   * 1   = right “ink box” edge.
   */
  x: number;

  /**
   * Vertical anchor line where this point sits.
   */
  y: GlyphSkeletonAnchor;
};

/**
 * One skeleton stroke between two anchor-based points.
 */
export type GlyphSkeletonStrokeDef = {
  from: GlyphSkeletonPoint;
  to: GlyphSkeletonPoint;
};

/**
 * Skeleton definition for a single letter.
 * The editor converts this into concrete strokes in canvas space.
 */
export type GlyphSkeletonDef = {
  letter: string;
  /**
   * Strokes (lines) that form the constructed base letter.
   */
  strokes: GlyphSkeletonStrokeDef[];
};

// ---------------------------------------------------------------------------
// Glyph width/left-bearing metrics for the “ink box”
// ---------------------------------------------------------------------------

/**
 * Simple width + left-bearing profile used to place the ink box for a letter.
 */
export type GlyphMetricProfile = {
  letter: string;
  // Fraction of canvas width used for the black shape
  // (e.g. 0.5 = narrow like "I", 0.8 = wide like "M").
  widthFactor: number;
  // Left side bearing as fraction of canvas width (0..1).
  leftBearingFactor: number;
};

/**
 * Fallback metric for letters not explicitly in GLYPH_METRICS.
 */
export const DEFAULT_GLYPH_METRIC: GlyphMetricProfile = {
  letter: '?',
  widthFactor: 0.7,
  leftBearingFactor: 0.15,
};

// ---------------------------------------------------------------------------
// Basic geometric primitives for the SVG editor
// ---------------------------------------------------------------------------

/**
 * Raw point in canvas pixel space.
 */
export type Point = {
  x: number;
  y: number;
};

/**
 * A concrete stroke drawn by the user or generated by skeleton logic.
 *
 * - Straight line: p0 → p1
 * - Quadratic curve: p0 → ctrl → p1
 */
export type Stroke = {
  id: string;
  p0: Point;
  p1: Point;
  /**
   * If present → quadratic Bézier control point.
   * If absent → stroke is a straight line.
   */
  ctrl?: Point;
  /**
   * Stroke width in pixels.
   */
  width: number;
};

/**
 * Group of strokes that move together.
 */
export type StrokeGroup = {
  id: string;
  strokeIds: string[];
};

// ---------------------------------------------------------------------------
// Handwriting line configuration
// ---------------------------------------------------------------------------

/**
 * Keys for the editable handwriting lines in the editor.
 *
 * (We keep "xHeight" here to stay readable in code; the logical anchor
 * name is still "xheight".)
 */
export type LineFactorKey =
  | 'majuscule'
  | 'ascender'
  | 'xHeight'
  | 'descender';

export type LineFactors = Record<LineFactorKey, number>;

/**
 * Default proportions for the five-line handwriting system, relative to
 * the main vertical band between top margin and baseline.
 *
 * These match your previous hard-coded numbers:
 * - baseline → x-height ≈ 0.35
 * - baseline → ascender ≈ 0.65
 * - baseline → majuscule ≈ 0.85
 * - descender band ≈ 0.20 below baseline
 */
export const DEFAULT_LINE_FACTORS: LineFactors = {
  xHeight: 0.20,
  ascender: 0.40,
  majuscule: 0.80,
  descender: 0.20,
};

// ---------------------------------------------------------------------------
// Canvas + editor modes
// ---------------------------------------------------------------------------

/**
 * Canonical canvas size used by the SVG editor.
 * If you ever change these, all helpers will use them consistently.
 */
export const SVG_CANVAS_WIDTH = 600;
export const SVG_CANVAS_HEIGHT = 600;

/**
 * Draw modes used by the editor toolbar and canvas.
 */
export type DrawMode = 'stroke' | 'circle'  | 'select';
