# Generated by Django 5.2.6 on 2025-09-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomolobeecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_demo_visible',
            field=models.BooleanField(default=False),
        ),
    ]
